### ISSUE TITLE
Package problem

### ISSUE THREAD

**Issue by whyqiliao** [NinevaStudios/AndroidGoodiesUnreal-SampleProject#1]
what is 
Plugin 'AndroidGoodies' failed to load because module 'AndroidGoodies' could not be found.Please ensure the plugin is properly install , otherwise consider disabling the plugin for this project.
in the project sln, it warnings that Modules must specify an explicit precompiled header (eg. PrivatePCHHeaderFile = "AndroidGoodiesTest.h") from UE 4.21 onwards.
Thx a lot!

**Comment by tustanivsky** [comment]
You have to place AndroidGoodies plugin (copy it from engine folder) inside YourProject/Plugins directory to avoid this issue.
Probably you’re using arm64. It's an old editor bug, UE doesn't place plugins within the app's contents for this configuration, so this workaround this required
